FROM node:20.11-alpine AS BUILD
WORKDIR /usr/src/app
ARG ROOT=/usr/src/app
ARG REPO=/usr/src/app/sites/samplekit.dev
ARG TZ=America/New_York
RUN apk --no-cache add curl tzdata
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY . $ROOT

CMD ["node", "hello.js"]
