name: Build image and publish to registry

on:
  push:
    branches: [main]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.gh
          tags: ghcr.io/${{ github.repository }}:latest
